# Generated by Django 4.0.6 on 2022-09-01 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_todo_is_active_alter_todo_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='pub_date',
        ),
    ]
