# Generated by Django 4.0.6 on 2022-09-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_todo_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='scores',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Отложено'),
        ),
    ]
